### PR TITLE
Switch read-heavy locks to shared ones

### PR DESCRIPTION
**Pull request by bluecmd**
I have a slight idea what I'm doing, but please apply a handful of skepticism
as concurrency is kinda easy to screw up. 

Allow fast iteration over locked lists when possible. It's only critical
that we lock the metric lists when updating them.

### CODE REVIEW

**Comment by bluecmd** [comment]
Ah, right - we're not using C++14.

How do you feel about using C++14 and bumping the GCC version to something newer?

**Comment by korfuri** [comment]
No objections to bumping to C++14 nowadays. I started with C++11 because it was more portable but that was a while ago, and nowadays people should be ready to use it. LGTM, will merge when the dependent commits are merged in #8 :)

**Comment by agnat** [comment]
This seems ready to land. @bluecmd, could you update the branch to not include the CMake build system?

**Comment by bluecmd** [comment]
It's the same commit, so it should go away when merged AFAIK. If not I can rebase.

**Comment by korfuri** [comment]
Sorry I forgot to merge that weeks ago! Merging now.

**Comment by agnat** [comment]
Turns out this breaks the Mac OS build:

```
prometheus_client/prometheus/collector.hh:70:20: error: 'shared_timed_mutex' is unavailable: introduced in macOS
      10.12
      mutable std::shared_timed_mutex mutex_;
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/shared_mutex:202:58: note: 
      'shared_timed_mutex' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS _LIBCPP_AVAILABILITY_SHARED_MUTEX shared_timed_mutex
                                                         ^
```

So we're going to need some sort of configure time detection and a couple of typedefs...

**Pull request merged**
